### ISSUE TITLE
Reorder Roles

### ISSUE THREAD

**Issue by Kaloell** [patrick-petersen/gw2_raid_setup#14]
To make the chart easier to read it helps to keep the same role in the same position.
In 100% of cases there is a Tempest.
In 100% of cases there is a Alacrity Renegade.
In 100% of cases there is a Chrono (90%) or a Boon Thief (10%).
In 90% of cases there is a Warrior.
Others can be added randomly.

**Comment by patrick-petersen** [comment]
The specific classes/ roles have changed, but the order is now generally the same
