### ISSUE TITLE
Create position for qadim 2 to post

### ISSUE THREAD

**Issue by Kaloell** [patrick-petersen/gw2_raid_setup#19]
There are specific positions for every role at qadim 2 i.e. 

> Pfeil/Herz: Nevra, Shrotty ; Kreis/Herz: Kalell, Alex ; Dreieck/Wirbel: Assa, Fynn, Ely ; Viereck/Stern: Lumi, Yasi, David

It should be possible to generate this from the setup, even if its just in the console.

**Comment by patrick-petersen** [comment]
Obsolete, ppl generally know where to go
